# 1번 과제 관심 있는 주제 데이터 찾기

* 데이터명: Social Media User Analysis, 미디어기기 이용빈도
* 데이터 특징
   * 출처:kaggle(https://www.kaggle.com/datasets/rockyt07/social-media-user-analysis),
 방송통계포털(https://www.mediastat.or.kr/statHtml/statHtml.do?orgId=005&tblId=DT_164002_B024&vw_cd=undefined&list_id=undefined&scrId=&seqNo=&language=ko&obj_var_id=undefined&itm_id=undefined&conn_path=I2&path=)

   * 분야: 미디어
   * 내용: `social media user analysis` 자료는 소셜 미디어 이용자의 특성             과 행동을 정밀하게 분석해야 할 때 유용하다. 약 155만 명 규모            로 나이,성별,국가,교육 수준 등의 기준에 따라 어떤 계층이 소            셜 미디어를 더 적극적으로 사용하는지 분석 가능하다. 표본 수            가 매우 크기 때문에 회귀분석, 군집분석 등 고급 분석 기법 적             용에도 적합하다.
   
   * 적용 분야: 소셜 미디어 이용자의 세부 특성과 이용 행태를 대규모로                   분석하여 타깃 마케팅이나 사회문화적 미디어 연구에 활용                  하기 적합하다.
   * 내용: `미디어기기 이용빈도` 자료는 전체 미디어 소비 구조와 매체별 이           용 현황을 파악해야 할 때 유용하다. 2024년 기준 데이터이므로             최근 미디어 이용 트렌트 설명에 신뢰도가 높으며 tv,라디오,신문           등 매체별 이용 빈도를 통해 어떤 계층이 어떤 미디어를 주로 소비        하는지 파악할 수 있고 미디어 환경 변화 분석에 이용할 수 있다.
   * 적용 분야: 계층별,세대별 미디어 매체 이용 빈도를 비교하여 미디어                   소비구조와 정책적 활용 방안을 분석하는 데 유용하다.

In [7]:
import pandas as pd
import numpys np

In [38]:
df1=pd.read_csv("Downloads/instagram_usage_lifestyle.csv")
df1.shape

(1547896, 58)

,user_id,app_name,age,gender,country,urban_rural,income_level,employment_status,education_level,relationship_status,...,last_login_date,average_session_length_minutes,content_type_preference,preferred_content_theme,privacy_setting_level,two_factor_auth_enabled,biometric_login_used,linked_accounts_count,subscription_status,user_engagement_score
0,1,Instagram,51,Female,India,Rural,High,Retired,Bachelor’s,Single,...,2025-11-02,5.0,Mixed,Tech,Private,Yes,No,0,Free,7.83
1,2,Instagram,64,Female,United Kingdom,Urban,Middle,Full-time employed,Other,Divorced,...,2025-03-22,14.8,Photos,Fashion,Public,No,No,3,Free,1.43
2,3,Instagram,41,Female,Canada,Urban,Middle,Student,Bachelor’s,In a relationship,...,2025-08-10,5.0,Mixed,Other,Public,Yes,Yes,1,Free,9.67
3,4,Instagram,27,Non-binary,South Korea,Urban,Middle,Unemployed,Master’s,In a relationship,...,2025-03-31,25.9,Stories,Tech,Private,No,No,1,Free,0.94
4,5,Instagram,55,Male,India,Urban,Upper-middle,Full-time employed,Bachelor’s,Single,...,2025-03-19,13.1,Videos,Food,Public,Yes,No,0,Free,1.03

In [44]:

df2=pd.read_csv("Downloads/미디어기기_이용_빈도_20260115165157.csv",encoding="cp949")
df2.shape

(55, 69)

In [45]:
df2.head()

,구분별(1),구분별(2),2024,2024.1,2024.2,2024.3,2024.4,2024.5,2024.6,2024.7,...,2024.57,2024.58,2024.59,2024.60,2024.61,2024.62,2024.63,2024.64,2024.65,2024.66
0,구분별(1),구분별(2),TV(지상파 종합·중계유선방송 위성TV IPTV시청 포함),TV(지상파 종합·중계유선방송 위성TV IPTV시청 포함),TV(지상파 종합·중계유선방송 위성TV IPTV시청 포함),TV(지상파 종합·중계유선방송 위성TV IPTV시청 포함),TV(지상파 종합·중계유선방송 위성TV IPTV시청 포함),TV(지상파 종합·중계유선방송 위성TV IPTV시청 포함),TV(지상파 종합·중계유선방송 위성TV IPTV시청 포함),라디오 수신기(인터넷/스마트기기 청취 제외),...,가정용게임기,가정용게임기,가정용게임기,가정용게임기,가정용게임기,VR,VR,VR,VR,VR
1,구분별(1),구분별(2),매일 (%),1주일에 5-6일 (%),1주일에 3-4일 (%),1주일에 1-2일 (%),한 달에 1-3일 (%),2-3달에 1-2일 이하 (%),전혀 안 봄/이용 안함 (%),매일 (%),...,1주일에 3-4일 (%),1주일에 1-2일 (%),한 달에 1-3일 (%),2-3달에 1-2일 이하 (%),전혀 안 봄/이용 안함 (%),1주일에 3-4일 (%),1주일에 1-2일 (%),한 달에 1-3일 (%),2-3달에 1-2일 이하 (%),전혀 안 봄/이용 안함 (%)
2,전체,소계,61.9,7.2,5.4,8.7,3.0,2.6,11.1,2.0,...,0.4,0.6,0.5,0.3,98.0,0.0,0.0,0.1,0.0,99.9
3,성별,남자,60.8,8.0,5.3,9.1,2.6,2.4,11.8,2.3,...,0.5,0.5,0.4,0.2,98.0,0.0,0.0,0.1,0.0,99.9
4,성별,여자,63.1,6.3,5.4,8.4,3.4,2.9,10.4,1.6,...,0.3,0.7,0.6,0.3,98.1,0.0,0.0,0.1,0.0,99.8